### PR TITLE
C++ solution of sales_by_match

### PR DESCRIPTION
**Pull request by Souronix44**
Can you please check and merge it @sohailg

### CODE REVIEW

**Comment by Souronix44** [comment]
@sohailg can you review and merge this

**Comment by Souronix44** [comment]
hey @sohailg can you please add hacktoberfest tags

**Comment by Souronix44** [comment]
Please add hacktoberfest tags I only need one PR @sohailg  and time is running out please do it within today night

**Comment by sohailg** [comment]
I've Already tagged hacktoberfest to this repo

**Comment by Souronix44** [comment]
thanks alot @sohailg

**Pull request merged**
